name: Build/release

on: push

permissions:
    contents: write

jobs:
    release:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest]

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v1

            - name: Install Node.js, NPM and Yarn
              uses: actions/setup-node@v1
              with:
                  node-version: 22

            - name: Compile Electron App
              uses: x6Pnda/action-electron-compiler@5bb5fdcf4265905ff090a1e0af241380b972f5ba
              with:
                  # GitHub token, automatically provided to the action
                  # (Optional)
                  github_token: ${{ secrets.github_token }}

                  # If the commit is tagged with a version (e.g. "v1.0.0"),
                  # (Optional)
                  release: ${{ startsWith(github.ref, 'refs/tags/v') }}

                  # Package manager. NPM, PNPM and Yarn supported. Install Yarn and PNPM yourself. Default is NPM
                  # (Optional)
                  package_manager: NPM

                  # Directory where NPM/Yarn commands should be run
                  package_root: elle-app

                  # Skip buiding the application
                  # (Optional)
                  skip_build: false
